production: 
  sessions: 
    default: 
      uri: <%= ENV['MONGOLAB_URI'] %>
      options:
        safe: true
        skip_version_check: true

development:

  sessions:

    default:


      uri: mongodb://panel:czerwonysufit@ds057877.mongolab.com:57877/dropsport
      options:
  options:

test:
  sessions:
    default:
      uri: mongodb://panel:czerwonysufit@ds057877.mongolab.com:57877/dropsport
      options:
        consistency: :strong
        max_retries: 1
        retry_interval: 0


