production: 
  sessions: 
    default: 
      uri: <%= ENV['MONGOLAB_URI'] %>
      options:
        safe: true
        raise_not_found_error: false
        skip_version_check: true
    writeable:
      uri: <%= ENV['MONGOLAB_URI_STAT'] %>
      options:
        safe: true
        raise_not_found_error: false
        skip_version_check: true



development:
  sessions:
    default:
      database: heroku_app16851511
      hosts:
        - localhost:27017
      options:
        raise_not_found_error: false
        consistency: :eventual

    writeable:
      database: statlogin
      hosts:
        -  localhost:27017
      options:
        raise_not_found_error: false
        consistency: strong


test:
  sessions:
    default:
      database: heroku_app16851511
      hosts:
        - localhost:27017
      options:
        raise_not_found_error: false
        consistency: :eventual
        max_retries: 1
        retry_interval: 0

    writeable:
      database: statlogin
      hosts:
        - localhost:27017
      options:
        raise_not_found_error: false
        consistency: :strong
        max_retries: 1
        retry_interval: 0


